import { constVal, buildCommonSetting, applyMacBuildSettings } from "./const_val.js";

var json = [{
	"var":[
		{"sdkPath":constVal.sdkPath},
		{"clangPath":constVal.clangPath},
		{"srcPath":constVal.srcPath},
		{"ndkIncludePath":constVal.ndkIncludePath},
		{"ndkBinPath":constVal.ndkBinPath},
		{"v8dir": constVal.v8dir},
		{"targetDir": constVal.targetDir},
		{"sysroot": constVal.sysroot},
	],
	"compile":{
		"ccompiler":"${clangPath}/clang.exe",
		"cppcompiler":"${clangPath}/clang++.exe",
			
		"include":[
			"${sdkPath}/include/c++/7.2.0",
			"${sdkPath}/include/c++/7.2.0/include",
			//"C:/cygwin64/usr/local/x86_64-unknown-linux-gnu/lib/gcc/x86_64-unknown-linux-gnu/7.2.0/include", // sse is compile error
			"${ndkIncludePath}",
			"${sdkPath}/include/c++/7.2.0/x86_64-unknown-linux-gnu/",
			"${srcPath}",
			"${sdkPath}/sysroot/usr/include",
			"${sdkPath}/sysroot/usr/",
			"${sdkPath}/sysroot/usr/include/linux",
			"${sysroot}/usr/include/cairo",
			"${sysroot}/usr/include/glib-2.0",
			"${sysroot}/usr/include/gtk-3.0",
			"${sysroot}/usr/include/gdk-pixbuf-2.0",
			"${sysroot}/usr/include/atk-1.0",
			"${sysroot}/usr/include/pango-1.0",
			"${sysroot}/usr/lib/x86_64-linux-gnu/glib-2.0/include",
			"${srcPath}/linux",
			"${srcPath}/gen/${v8dir}/include",
			"${srcPath}/${v8dir}",
			"${srcPath}/${v8dir}/include",
			"${srcPath}/electron",
			"${srcPath}/third_party/skia/include/core",
			"${srcPath}/third_party/skia/include/config",
			"${srcPath}/third_party/skia/include/codec",
			"${srcPath}/third_party/skia/include/device",
			"${srcPath}/third_party/skia/include/effects",
			"${srcPath}/third_party/skia/include/images",
			"${srcPath}/third_party/skia/include/pathops",
			"${srcPath}/third_party/skia/include/ports",
			"${srcPath}/third_party/skia/include/private",
			"${srcPath}/third_party/skia/include/utils",
			"${srcPath}/third_party/skia/include/gpu",
			"${srcPath}/third_party/",
			"${srcPath}/third_party/zlib",
			"${srcPath}/node/openssl/openssl/include",
			"${srcPath}/node/openssl",
			"${srcPath}/node/uv/src",
			"${srcPath}/node/cares/include",
			"${srcPath}/node/cares/config/linux",
			"${srcPath}/node/uv/include"
		],
		"prebuildSrc":[
			//"${srcPath}/electron/common/asar/ScopedTemporaryFile.cpp",
			//"${srcPath}/electron/browser/api/ApiSession.cpp",
			//"${srcPath}/electron/common/asar/Archive.cpp",
			//"${srcPath}/electron/common/api/ApiAsar.cpp",
			"${srcPath}/electron/browser/api/ApiWebContents.cpp",
			"${srcPath}/electron/browser/api/ApiBrowserWindow.cpp",
			"${srcPath}/electron/browser/api/ApiApp.cpp",
			//"${srcPath}/electron/renderer/api/ApiRendererIpc.cpp",
			//"${srcPath}/electron/common/NodeThread.cpp",
			//"${srcPath}/electron/common/NodeBinding.cpp",
			//"${srcPath}/electron/common/ThreadCallWrap.cpp",
			"${srcPath}/electron/common/gin_helper/arguments.cpp",
			"${srcPath}/electron/common/gin_helper/converter.cpp",
			"${srcPath}/electron/common/gin_helper/dictionary.cpp",
			"${srcPath}/electron/common/gin_helper/function_template.cpp",
			"${srcPath}/electron/common/gin_helper/interceptor.cpp",
			"${srcPath}/electron/common/gin_helper/object_template_builder.cpp",
			"${srcPath}/electron/common/gin_helper/per_isolate_data.cpp",
			"${srcPath}/electron/common/gin_helper/wrappable.cpp",
			"${srcPath}/electron/common/api/ApiScreen.cpp",
			"${srcPath}/electron/browser/api/ApiDownloadItem.cpp",
			"${srcPath}/electron/Electron.cpp"
		],
		"src":[
			"${srcPath}/electron/renderer/api/ApiContextBridge.cpp",
			"${srcPath}/electron/browser/api/ApiWebContents.cpp",
			"${srcPath}/electron/browser/api/WindowList.cpp",
			"${srcPath}/electron/browser/api/ApiApp.cpp",
			"${srcPath}/electron/common/OptionsSwitches.cpp",
			"${srcPath}/electron/browser/api/ApiElectron.cpp",
			"${srcPath}/electron/browser/api/ApiMenu.cpp",
			"${srcPath}/electron/browser/api/ApiNativeTheme.mm",
			"${srcPath}/electron/common/NodeThread.cpp",
			"${srcPath}/electron/common/NodeBinding.cpp",
			"${srcPath}/electron/common/AtomCommandLine.cpp",
			"${srcPath}/electron/renderer/api/ApiRendererIpc.cpp",
			"${srcPath}/electron/common/IdLiveDetect.cpp",
			"${srcPath}/electron/common/api/EventEmitter.cpp",
			"${srcPath}/electron/common/api/EventEmitterCaller.cpp",
			"${srcPath}/electron/common/api/Event.cpp",
			"${srcPath}/electron/common/gin_helper/arguments.cpp",
			"${srcPath}/electron/common/gin_helper/converter.cpp",
			"${srcPath}/electron/common/gin_helper/dictionary.cpp",
			"${srcPath}/electron/common/gin_helper/function_template.cpp",
			"${srcPath}/electron/common/gin_helper/interceptor.cpp",
			"${srcPath}/electron/common/gin_helper/object_template_builder.cpp",
			"${srcPath}/electron/common/gin_helper/per_isolate_data.cpp",
			"${srcPath}/electron/common/gin_helper/wrappable.cpp",
			"${srcPath}/electron/common/api/RemoteCallbackFreer.cpp",
			"${srcPath}/electron/common/api/RemoteObjectFreer.cpp",
			"${srcPath}/electron/common/api/ObjectLifeMonitor.cpp",
			"${srcPath}/electron/common/api/ApiV8Util.cpp",
			//"${srcPath}/electron/common/api/ApiShell.cpp",
			//"${srcPath}/electron/common/PlatformUtilWin.cpp",
			"${srcPath}/electron/common/api/ApiOriginalFs.cpp",
			"${srcPath}/electron/common/api/ApiScreen.cpp",
			"${srcPath}/electron/renderer/api/ApiWebFrame.cpp",
			"${srcPath}/electron/Electron.cpp",
			"${srcPath}/electron/common/api/ApiIntlCollator.cpp",
			//"${srcPath}/electron/browser/api/ApiDialag.cpp",
			"${srcPath}/electron/common/api/ApiAsar.cpp",
			"${srcPath}/electron/common/asar/AsarUtil.cpp",
			"${srcPath}/electron/common/asar/Archive.cpp",
			"${srcPath}/electron/common/asar/ScopedTemporaryFile.cpp",
			"${srcPath}/electron/browser/api/ApiProtocol.cpp",
			//"${srcPath}/electron/browser/api/ApiTray.cpp",
			//"${srcPath}/electron/common/SystemTray.cpp",
			//"${srcPath}/content/ui/WebDropSource.cpp",
			//"${srcPath}/content/ui/ClipboardUtil.cpp",
			//"${srcPath}/electron/common/api/ApiNativeImage.cpp",
			//"${srcPath}/electron/renderer/WebviewPluginImpl.cpp",
			//"${srcPath}/electron/renderer/WebviewPlugin.cpp",
			//"${srcPath}/electron/common/InitGdiPlus.cpp",
			//"${srcPath}/electron/common/api/ApiClipboard.cpp",
			//"${srcPath}/content/ui/WCDataObject.cpp",
			//"${srcPath}/electron/NapiStub.cpp",
			"${srcPath}/electron/browser/api/ApiBrowserView.cpp",
			"${srcPath}/electron/browser/api/ApiBrowserWindow.cpp",
			"${srcPath}/electron/common/ThreadCallWrap.cpp",
			"${srcPath}/electron/browser/api/ApiSession.cpp",
			"${srcPath}/electron/browser/api/ApiWebRequest.cpp",
			"${srcPath}/electron/renderer/api/ObjectCache.cpp",
			"${srcPath}/gin/promise.cc",
			"${srcPath}/gin/microtasks_scope.cc",
			"${srcPath}/electron/browser/api/ApiDownloadItem.cpp"

		],
		// 
		"cmd":[
			//"--target=x86_64-linux-guneabi", 
			"-std=c++20",
			"-fno-exceptions",
			"-fms-extensions",
			//"-fshort-wchar",
			"-D__POSIX__=1",
			"-DHAVE_CONFIG_H",
			"-D_GNU_SOURCE",
			"-DUSE_AURA",
			"-DOS_LINUX_FOR_WIN",
			"-DINSIDE_BLINK",
			"-DBLINK_IMPLEMENTATION",
			"-DENABLE_WKE",
			"-D_HAS_CONSTEXPR=0",
			"-D_CRT_SECURE_NO_WARNINGS",
			"-DNODE_WANT_INTERNALS",
			"-DHAVE_OPENSSL",
			"-DCARES_STATICLIB",
			"-DBUILDING_UV_SHARED",
			"-DSK_SUPPORT_LEGACY_CREATESHADER_PTR=1",
			"-DSK_SUPPORT_LEGACY_TYPEFACE_PTR=1",
			"-DENABLE_WKE=1",
			"-DENABLE_MB=1",
			"-DENABLE_NODEJS=1"
		],
		"objdir":"${srcPath}/out/tmp/electron/${targetDir}",
		"outdir":"${srcPath}/out/${targetDir}",
		"target":"libelectron.a",
		"beginLibs":[
		],
		"linkerCmd":[],
		"endLibs":[
		],
		"linker":constVal.linker//"${ndkBinPath}/ar.exe"
	}
}];

if (constVal.isMac) {
	json[0].compile.include.push("${srcPath}/mac");
	json[0].compile.include.push("${srcPath}/gen");
	json[0].compile.include.push("${srcPath}/gen/v8/include");
	json[0].compile.include.push("${srcPath}/v8/include");
	json[0].compile.include.push("${srcPath}/third_party/libnode/src");
	json[0].compile.include.push("${srcPath}/third_party/libuv/include");
	json[0].compile.include.push("${srcPath}/third_party/abseil-cpp");
	json[0].compile.include.push("${srcPath}/base/allocator/partition_allocator/src");
	json[0].compile.include.push("${srcPath}/gen/base/allocator/partition_allocator/src");
	applyMacBuildSettings(json, { v8: true });
	json[0].compile.include.push("${srcPath}/content");
	json[0].compile.include.push("${srcPath}/linux");
	json[0].compile.cmd.push("-DV8_HAVE_TARGET_OS");

	const macPowerMonitorSrc = "${srcPath}/electron/browser/api/ApiPowerMonitor.cpp";
	const macPowerSaveBlockerSrc = "${srcPath}/electron/browser/api/ApiPowerSaveBlocker.cpp";
	const macPowerMonitorIdleSrc = [
		"${srcPath}/ui/base/idle/idle.cc",
		"${srcPath}/ui/base/idle/idle_internal.cc",
		"${srcPath}/ui/base/idle/idle_mac.mm",
	];
	const macElectronLinkedBindingSrc = new Set([
		"${srcPath}/electron/browser/api/ApiElectron.cpp",
		"${srcPath}/electron/browser/api/ApiNativeTheme.mm",
		macPowerMonitorSrc,
		macPowerSaveBlockerSrc,
		"${srcPath}/electron/browser/api/ApiProtocol.cpp",
		"${srcPath}/electron/browser/api/WindowList.cpp",
		"${srcPath}/electron/common/AtomCommandLine.cpp",
		"${srcPath}/electron/common/IdLiveDetect.cpp",
		"${srcPath}/electron/common/OptionsSwitches.cpp",
		"${srcPath}/electron/common/api/ApiAsar.cpp",
		"${srcPath}/electron/common/api/ApiIntlCollator.cpp",
		"${srcPath}/electron/common/api/ApiOriginalFs.cpp",
		"${srcPath}/electron/common/api/ApiScreen.cpp",
		"${srcPath}/electron/common/api/ApiV8Util.cpp",
		"${srcPath}/electron/common/api/Event.cpp",
		"${srcPath}/electron/common/api/EventEmitter.cpp",
		"${srcPath}/electron/common/api/EventEmitterCaller.cpp",
		"${srcPath}/electron/common/gin_helper/arguments.cpp",
		"${srcPath}/electron/common/gin_helper/converter.cpp",
		"${srcPath}/electron/common/gin_helper/dictionary.cpp",
		"${srcPath}/electron/common/gin_helper/function_template.cpp",
		"${srcPath}/electron/common/gin_helper/interceptor.cpp",
		"${srcPath}/electron/common/gin_helper/object_template_builder.cpp",
		"${srcPath}/electron/common/gin_helper/per_isolate_data.cpp",
		"${srcPath}/electron/common/gin_helper/wrappable.cpp",
		"${srcPath}/electron/common/api/ObjectLifeMonitor.cpp",
		"${srcPath}/electron/common/api/RemoteCallbackFreer.cpp",
		"${srcPath}/electron/common/api/RemoteObjectFreer.cpp",
		"${srcPath}/electron/renderer/api/ApiRendererIpc.cpp",
		"${srcPath}/electron/renderer/api/ObjectCache.cpp",
		...macPowerMonitorIdleSrc,
	]);
	json[0].compile.src = json[0].compile.src.filter(src => macElectronLinkedBindingSrc.has(src));
	json[0].compile.src.push(macPowerMonitorSrc);
	json[0].compile.src.push(macPowerSaveBlockerSrc);
	json[0].compile.src.push(...macPowerMonitorIdleSrc);
	json[0].compile.src = [...new Set(json[0].compile.src)];
	json[0].compile.prebuildSrc = json[0].compile.prebuildSrc.filter(src => macElectronLinkedBindingSrc.has(src));
	json[0].compile.prebuildSrc.push(macPowerMonitorSrc);
	json[0].compile.prebuildSrc.push(macPowerSaveBlockerSrc);
	json[0].compile.prebuildSrc.push(...macPowerMonitorIdleSrc);
	json[0].compile.prebuildSrc = [...new Set(json[0].compile.prebuildSrc)];
}

buildCommonSetting(json);
